export const endopint = {
    registrarUsuario: 'usuario',
    login: 'usuario/login',
    libro: 'libro',
    libroPaginacion: 'libro/paginado',
    usuario: 'usuario/one',
    modulo: 'permiso_modulo',
    ruta: 'permiso_ruta',
    rol: 'permiso_rol',
    rutaParametro: 'permiso_ruta/relacion',
    permisoParametro: 'permiso_parametro',
    permiso: 'permiso',
    metodosHttp: 'permiso_ruta/metodos_http',
    tiposDeDatos: 'permiso_parametro/tipos_de_datos',
    prestamo: 'inventario/prestamo',
    devolucion: 'inventario/devolucion',
    prestamos: 'inventario/prestamo/all',
    devoluciones: 'inventario/devolucion/all',
}
